/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['1935410016_(liten_solsten)']: THREE.Mesh
  }
  materials: {
    ['Material #47']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/sunstone-2-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['1935410016_(liten_solsten)'].geometry} material={materials['Material #47']} scale={0} />
    </group>
  )
}

useGLTF.preload('/sunstone-2-transformed.glb')
