/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1923060010_(chalchiutlicue)']: THREE.Mesh;
  };
  materials: {
    ['Material #30']: THREE.MeshStandardMaterial;
  };
};

const Chalchiutlicue = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    '/chalchiutlicue-transformed.glb'
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1923060010_(chalchiutlicue)'].geometry}
        material={materials['Material #30']}
        scale={0.02}
        position={[0, -1.3, 0]}
      />
    </group>
  );
};

export default Chalchiutlicue;

useGLTF.preload('/chalchiutlicue-transformed.glb');
