/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1935082774_(maskskärva)']: THREE.Mesh;
  };
  materials: {
    ['Material #29']: THREE.MeshStandardMaterial;
  };
};

const MaskIncense = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/maskskärva-transformed.glb'
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="1935082774_(maskskärva)"
        geometry={nodes['1935082774_(maskskärva)'].geometry}
        material={materials['Material #29']}
        position={[0, -4, -0.3]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.02}
      />
    </group>
  );
};

export default MaskIncense;

useGLTF.preload('/maskskärva-transformed.glb');
