/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1923060589_(maya-figur)']: THREE.Mesh;
  };
  materials: {
    ['Material #31']: THREE.MeshStandardMaterial;
  };
};

const Maya = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    '/maya-transformed.glb'
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1923060589_(maya-figur)'].geometry}
        material={materials['Material #31']}
        position={[0, -1.7, 0]}
        scale={0.02}
      />
    </group>
  );
};

export default Maya;

useGLTF.preload('/maya-transformed.glb');
