/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

type DreiGLTF = typeof useGLTF & {
  nodes: Record<string, any>;
  materials: Record<string, any>;
};

export const Maya = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    '/maya-transformed.glb'
  ) as unknown as DreiGLTF;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1923060589_(maya-figur)'].geometry}
        material={materials['Material #31']}
        position={[0, -1.5, 0]}
        scale={0.02}
      />
    </group>
  );
};

useGLTF.preload('/maya-transformed.glb');
