/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const Olmek = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/olmek.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1974180001_(olmek-figur)'].geometry}
        material={materials['Material #33.001']}
        rotation={[1.59, 0, 3.05]}
        scale={[10.27, 10.27, 10.27]}
      />
    </group>
  );
};

useGLTF.preload('/olmek.glb');
