/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1974180001_(olmek-figur)']: THREE.Mesh;
  };
  materials: {
    ['Material #33.001']: THREE.MeshStandardMaterial;
  };
};

const Olmek = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/olmek-transformed.glb') as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1974180001_(olmek-figur)'].geometry}
        material={materials['Material #33.001']}
        rotation={[1.59, 0, 3.05]}
        scale={[10.27, 10.27, 10.27]}
      />
    </group>
  );
};

export default Olmek;

useGLTF.preload('/olmek-transformed.glb');
