/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1911070002']: THREE.Mesh;
  };
  materials: {
    ['Material #25']: THREE.MeshStandardMaterial;
  };
};

const Quetzalcoatl = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    '/quetzalcoatl-2-transformed.glb'
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="1911070002"
        geometry={nodes['1911070002'].geometry}
        material={materials['Material #25']}
        scale={0.01}
        position={[0, -1.8, 0]}
      />
    </group>
  );
};

export default Quetzalcoatl;

useGLTF.preload('/quetzalcoatl-2-transformed.glb');
