/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const SacrificalStone = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/sacrificialstone-transformed.glb');

  useEffect(() => {
    group.current.rotation.x = 90;
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1936060002_(offersten)'].geometry}
        material={materials['Material #48']}
        position={[0, -0.2, 0]}
        scale={0.15}
      />
    </group>
  );
};

useGLTF.preload('/sacrificialstone-transformed.glb');
