/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1923080684_(skärva)']: THREE.Mesh;
  };
  materials: {
    ['Material #39']: THREE.MeshStandardMaterial;
  };
};

export const Skarva = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/skarva-transformed.glb') as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1923080684_(skärva)'].geometry}
        material={materials['Material #39']}
        scale={0.025}
        position={[0, -1.5, 0]}
      />
    </group>
  );
};

useGLTF.preload('/skarva-transformed.glb');
