/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1935410016_(liten_solsten)']: THREE.Mesh;
  };
  materials: {
    ['Material #47']: THREE.MeshStandardMaterial;
  };
};

const SunStoneSmall = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/sunstone-small-transformed.glb'
  ) as GLTFResult;

  useEffect(() => {
    if (group.current) {
      group.current.rotation.x = 45.4;
    }
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1935410016_(liten_solsten)'].geometry}
        material={materials['Material #47']}
        scale={0.03}
      />
    </group>
  );
};

export default SunStoneSmall;

useGLTF.preload('/sunstone-small-transformed.glb');
