/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1962690010_(toltek-figur)']: THREE.Mesh;
  };
  materials: {
    ['Material #25.001']: THREE.MeshStandardMaterial;
  };
};

const Toltek = ({ ...props }) => {
  const group = useRef(null);
  const { nodes, materials } = useGLTF('/toltek-transformed.glb') as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1962690010_(toltek-figur)'].geometry}
        material={materials['Material #25.001']}
        position={[0.02, -1.4, 0.1]}
        scale={0.04}
      />
    </group>
  );
};

export default Toltek;

useGLTF.preload('/toltek-transformed.glb');
