/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const Toltek = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/toltek-transformed.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1962690010_(toltek-figur)'].geometry}
        material={materials['Material #25.001']}
        position={[0.02, -0.9, 0.01]}
        scale={0.04}
      />
    </group>
  );
};

useGLTF.preload('/toltek-transformed.glb');
