/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { a, useSpring } from '@react-spring/three';

export const Toltek = ({ ...props }) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('/toltek-transformed.glb');

  const { ...animation } = useSpring({
    from: {
      scale: [0, 0, 0],
      rotation: [0, -10, 0],
    },
    to: {
      scale: [1, 1, 1],
      rotation: [0, 0, 0],
    },
    config: { mass: 40, tension: 350, friction: 300, precision: 0.00001 },
  });

  return (
    <a.group {...animation}>
      <a.group ref={group} {...props} dispose={null}>
        <mesh
          geometry={nodes['1962690010_(toltek-figur)'].geometry}
          material={materials['Material #25.001']}
          position={[0.02, -0.9, 0.01]}
          scale={0.04}
        />
      </a.group>
    </a.group>
  );
};

useGLTF.preload('/toltek-transformed.glb');
