/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['1923060545_(xolo)']: THREE.Mesh;
  };
  materials: {
    ['Material #27']: THREE.MeshStandardMaterial;
  };
};

const Xolo = ({ ...props }: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/xolo-transformed.glb') as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['1923060545_(xolo)'].geometry}
        material={materials['Material #27']}
        position={[0, -1, 0]}
        scale={0.007}
      />
    </group>
  );
};

export default Xolo;

useGLTF.preload('/xolo-transformed.glb');
