/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Scottish Maritime Museum (https://sketchfab.com/ScottishMaritimeMuseum)
license: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
source: https://sketchfab.com/3d-models/figurehead-of-hms-prince-of-wales-55101f971ed74f03a48045f23411bacd
title: Figurehead of HMS "Prince Of Wales"
*/

import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    group.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20
    group.current.rotation.x = Math.cos(t / 4) / 8
    group.current.rotation.y = Math.sin(t / 4) / 8
    group.current.position.y = (1 + Math.sin(t / 1.5)) / 10
  })

  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.15, -1.52, -1.64]} rotation={[1.59, 0.93, -3.13]}>
          {/* <PresentationControls
            global={true} // Spin globally or by dragging the model
            snap={false} // Snap-back to center (can also be a spring config)
            speed={3} // Speed factor
            zoom={1} // Zoom factor when half the polar-max is reached
            rotation={[0.24, 0, 0]} // Default rotation
            polar={[0, Math.PI / 2]} // Vertical limits
            azimuth={[-Infinity, Infinity]} // Horizontal limits
            config={{ mass: 1, tension: 170, friction: 26 }} // Spring config
          > */}
          <mesh
            geometry={nodes.mesh_0.geometry}
            material={materials.material_0}
          />
          {/* </PresentationControls> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
